export const blogPosts = [
  {
    id: 1,
    title: "Building Secure Web Applications: Best Practices",
    excerpt:
      "Learn the essential security practices every developer should implement to protect web applications from common vulnerabilities.",
    image: "/placeholder.svg?height=300&width=500",
    date: "April 10, 2025",
    readTime: "8 min read",
    category: "Security",
    slug: "building-secure-web-applications",
    featured: true,
  },
  {
    id: 2,
    title: "Integrating AI Features into Your Next.js Application",
    excerpt:
      "A step-by-step guide to adding AI-powered features to your Next.js projects using the latest AI SDKs and APIs.",
    image: "/placeholder.svg?height=300&width=500",
    date: "March 25, 2025",
    readTime: "12 min read",
    category: "AI",
    slug: "integrating-ai-features-nextjs",
    featured: true,
  },
  {
    id: 3,
    title: "The Future of Mobile Development in Africa",
    excerpt:
      "Exploring the growing mobile development ecosystem in Africa and opportunities for developers in the region.",
    image: "/placeholder.svg?height=300&width=500",
    date: "March 15, 2025",
    readTime: "10 min read",
    category: "Mobile",
    slug: "future-mobile-development-africa",
    featured: false,
  },
  {
    id: 4,
    title: "Optimizing React Performance: Advanced Techniques",
    excerpt: "Dive into advanced optimization strategies to make your React applications blazing fast.",
    image: "/placeholder.svg?height=300&width=500",
    date: "February 28, 2025",
    readTime: "15 min read",
    category: "React",
    slug: "optimizing-react-performance",
    featured: false,
  },
  {
    id: 5,
    title: "Cybersecurity Essentials for Web Developers",
    excerpt: "A comprehensive guide to protecting your web applications from common security threats.",
    image: "/placeholder.svg?height=300&width=500",
    date: "February 15, 2025",
    readTime: "11 min read",
    category: "Security",
    slug: "cybersecurity-essentials-web-developers",
    featured: false,
  },
  {
    id: 6,
    title: "Building Cross-Platform Mobile Apps with React Native",
    excerpt: "Learn how to create efficient, performant mobile applications that work on both iOS and Android.",
    image: "/placeholder.svg?height=300&width=500",
    date: "January 30, 2025",
    readTime: "14 min read",
    category: "Mobile",
    slug: "cross-platform-mobile-apps-react-native",
    featured: false,
  },
  {
    id: 7,
    title: "Getting Started with AI Development in Nigeria",
    excerpt: "Resources, opportunities, and challenges for AI developers in Nigeria and across Africa.",
    image: "/placeholder.svg?height=300&width=500",
    date: "January 15, 2025",
    readTime: "9 min read",
    category: "AI",
    slug: "ai-development-nigeria",
    featured: false,
  },
  {
    id: 8,
    title: "Modern Authentication Patterns for Web Applications",
    excerpt: "Implementing secure, user-friendly authentication in your web applications.",
    image: "/placeholder.svg?height=300&width=500",
    date: "December 28, 2024",
    readTime: "13 min read",
    category: "Security",
    slug: "modern-authentication-patterns",
    featured: false,
  },
]
